/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import clases.Global;
import clases.Modelo;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ceperro
 */
public final class Maquinas extends javax.swing.JFrame {

    /**
     * Creates new form Mantenedor1
     */
    DefaultTableModel model;
    ArrayList<String> videos = new ArrayList<>();
    ArrayList<String> macs = new ArrayList<>();
    ArrayList<String> tipo = new ArrayList<>();
    ArrayList<String> dueno = new ArrayList<>();

    public Maquinas() {
        this.setUndecorated(true);
        initComponents();
        CargarTabla(null, "todo");
        pnlModuloEliminar.setVisible(false);
        new Cargar(cmbMac, "mac", macs).execute();
        new Cargar(cmbDueno, "propietario", dueno).execute();
        new Cargar(cmbTipo, "tipo", tipo).execute();
       CambiarColor();
        this.setOpacity(0.98f);


        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        pnlBarra = new javax.swing.JPanel();
        pnlBotonera = new javax.swing.JPanel();
        btnAgregarMaquina = new javax.swing.JButton();
        BtnEliminarMaquina = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlModuloEliminar = new javax.swing.JPanel();
        pnlFiltrarPor = new javax.swing.JPanel();
        cmbMac = new javax.swing.JComboBox<>();
        cmbDueno = new javax.swing.JComboBox<>();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlInformacionMa = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMostrarEliminar = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        listVideos = new javax.swing.JList<>();
        btnEliminar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnlModuloAgregar = new javax.swing.JPanel();
        pnlAgregarMaquina = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        txtLocacion = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtPropietario = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtHamachi = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtMac = new javax.swing.JTextField();
        rbNo = new javax.swing.JRadioButton();
        rbSi = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        pnlInformacionPreliminar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAgregar = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        pnlBarra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlBarraLayout = new javax.swing.GroupLayout(pnlBarra);
        pnlBarra.setLayout(pnlBarraLayout);
        pnlBarraLayout.setHorizontalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBarraLayout.setVerticalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnAgregarMaquina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1488844214_ic_add_to_photos_48px.png"))); // NOI18N
        btnAgregarMaquina.setText("Agregar Maquina");
        btnAgregarMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMaquinaActionPerformed(evt);
            }
        });

        BtnEliminarMaquina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1487291347_trash_bin.png"))); // NOI18N
        BtnEliminarMaquina.setText("Eliminar Maquina");
        BtnEliminarMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarMaquinaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1489446150_other-arrow-left-other-glyph.png"))); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1489513442_Cancel.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoneraLayout = new javax.swing.GroupLayout(pnlBotonera);
        pnlBotonera.setLayout(pnlBotoneraLayout);
        pnlBotoneraLayout.setHorizontalGroup(
            pnlBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotoneraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnAgregarMaquina)
                .addGap(26, 26, 26)
                .addComponent(BtnEliminarMaquina)
                .addGap(29, 29, 29)
                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBotoneraLayout.setVerticalGroup(
            pnlBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotoneraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEliminarMaquina)
                    .addComponent(btnAgregarMaquina)
                    .addComponent(jButton1)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pnlModuloEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar & Visualizar"));

        pnlFiltrarPor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Filtrar Por..."));

        cmbMac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMacActionPerformed(evt);
            }
        });

        cmbDueno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDuenoActionPerformed(evt);
            }
        });

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        jLabel8.setText("Mac");

        jLabel11.setText("Marca");

        jLabel12.setText("Tipo");

        javax.swing.GroupLayout pnlFiltrarPorLayout = new javax.swing.GroupLayout(pnlFiltrarPor);
        pnlFiltrarPor.setLayout(pnlFiltrarPorLayout);
        pnlFiltrarPorLayout.setHorizontalGroup(
            pnlFiltrarPorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrarPorLayout.createSequentialGroup()
                .addGroup(pnlFiltrarPorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFiltrarPorLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel8))
                    .addGroup(pnlFiltrarPorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(cmbMac, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81)
                .addGroup(pnlFiltrarPorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFiltrarPorLayout.createSequentialGroup()
                        .addComponent(cmbDueno, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(pnlFiltrarPorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(267, 267, 267)
                        .addComponent(jLabel12)
                        .addGap(177, 177, 177))))
        );
        pnlFiltrarPorLayout.setVerticalGroup(
            pnlFiltrarPorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrarPorLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(pnlFiltrarPorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(pnlFiltrarPorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)))
                .addGap(6, 6, 6)
                .addGroup(pnlFiltrarPorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFiltrarPorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbDueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInformacionMa.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Informacion Maquinas"));

        tablaMostrarEliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaMostrarEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMostrarEliminarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaMostrarEliminar);

        listVideos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listVideos);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/magic-wand-20.png"))); // NOI18N
        btnEliminar.setText("Eliminar Maquina");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_see-20 (1).png"))); // NOI18N
        jButton2.setText("Mostrar Todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInformacionMaLayout = new javax.swing.GroupLayout(pnlInformacionMa);
        pnlInformacionMa.setLayout(pnlInformacionMaLayout);
        pnlInformacionMaLayout.setHorizontalGroup(
            pnlInformacionMaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionMaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlInformacionMaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInformacionMaLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(419, 419, 419)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlInformacionMaLayout.setVerticalGroup(
            pnlInformacionMaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionMaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInformacionMaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnlInformacionMaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(jButton2))
                .addGap(250, 250, 250))
        );

        javax.swing.GroupLayout pnlModuloEliminarLayout = new javax.swing.GroupLayout(pnlModuloEliminar);
        pnlModuloEliminar.setLayout(pnlModuloEliminarLayout);
        pnlModuloEliminarLayout.setHorizontalGroup(
            pnlModuloEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModuloEliminarLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(pnlModuloEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlInformacionMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFiltrarPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        pnlModuloEliminarLayout.setVerticalGroup(
            pnlModuloEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModuloEliminarLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(pnlFiltrarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlInformacionMa, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlModuloAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Maquina"));

        pnlAgregarMaquina.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Agregar Maquina"));

        jLabel9.setText("Mac :");

        jLabel1.setText("Nombre :");

        jLabel2.setText("Hamachi Ip :");

        jLabel3.setText("Tipo :");

        jLabel4.setText("Propietario :");

        jLabel5.setText("Direccion :");

        jLabel6.setText("Locacion :");

        jLabel7.setText("Ubicacion:");

        txtHamachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHamachiActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMacActionPerformed(evt);
            }
        });

        btnGroup.add(rbNo);
        rbNo.setText("No");
        rbNo.setName("rb"); // NOI18N
        rbNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoActionPerformed(evt);
            }
        });

        btnGroup.add(rbSi);
        rbSi.setText("Si");
        rbSi.setName("rb"); // NOI18N
        rbSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSiActionPerformed(evt);
            }
        });

        jLabel10.setText("¿Actualizacion Automatica?");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1489445585_vendingmachine.png"))); // NOI18N
        btnAgregar.setText("Add");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarMaquinaLayout = new javax.swing.GroupLayout(pnlAgregarMaquina);
        pnlAgregarMaquina.setLayout(pnlAgregarMaquinaLayout);
        pnlAgregarMaquinaLayout.setHorizontalGroup(
            pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarMaquinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29)
                .addGroup(pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLocacion)
                    .addComponent(txtDireccion)
                    .addComponent(txtPropietario)
                    .addComponent(txtTipo)
                    .addGroup(pnlAgregarMaquinaLayout.createSequentialGroup()
                        .addComponent(txtMac, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNombre)
                    .addComponent(txtHamachi)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(69, 69, 69))
            .addGroup(pnlAgregarMaquinaLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarMaquinaLayout.createSequentialGroup()
                .addGroup(pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAgregarMaquinaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(pnlAgregarMaquinaLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(rbSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbNo)))
                .addGap(165, 165, 165))
        );
        pnlAgregarMaquinaLayout.setVerticalGroup(
            pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarMaquinaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHamachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAgregarMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbNo)
                    .addComponent(rbSi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlInformacionPreliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Informacion Preliminar"));

        tablaAgregar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAgregar);

        javax.swing.GroupLayout pnlInformacionPreliminarLayout = new javax.swing.GroupLayout(pnlInformacionPreliminar);
        pnlInformacionPreliminar.setLayout(pnlInformacionPreliminarLayout);
        pnlInformacionPreliminarLayout.setHorizontalGroup(
            pnlInformacionPreliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionPreliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlInformacionPreliminarLayout.setVerticalGroup(
            pnlInformacionPreliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionPreliminarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Faster Intelligent ®");

        javax.swing.GroupLayout pnlModuloAgregarLayout = new javax.swing.GroupLayout(pnlModuloAgregar);
        pnlModuloAgregar.setLayout(pnlModuloAgregarLayout);
        pnlModuloAgregarLayout.setHorizontalGroup(
            pnlModuloAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModuloAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModuloAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModuloAgregarLayout.createSequentialGroup()
                        .addComponent(pnlAgregarMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(pnlInformacionPreliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnlModuloAgregarLayout.setVerticalGroup(
            pnlModuloAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModuloAgregarLayout.createSequentialGroup()
                .addGroup(pnlModuloAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModuloAgregarLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(pnlInformacionPreliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlAgregarMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14))
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Primary_logo_on_transparent_432x63.png"))); // NOI18N

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlModuloAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlModuloEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(pnlBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(pnlModuloAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(pnlModuloEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbNoActionPerformed

    private void rbSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbSiActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        int actualizar = 0;
        if (rbSi.isSelected()) {
            actualizar = 1;
        }
        try {
            Connection con = Conexion.getConexionMySQL();
            Statement s = con.createStatement();
            try {
                s.executeUpdate("insert into maquinas (mac,nombre,hamachi_ip,tipo,propietario,direccion,locacion,ubicacion,actualizar)" + " values('" + Global.Encriptar(txtMac.getText()) + "','"
                        + Global.Encriptar(txtNombre.getText()) + "','" + Global.Encriptar(txtHamachi.getText()) + "','" + Global.Encriptar(txtTipo.getText()) + "','" + Global.Encriptar(txtPropietario.getText()) + "','"
                        + Global.Encriptar(txtDireccion.getText()) + "','" + Global.Encriptar(txtLocacion.getText()) + "','" + Global.Encriptar(txtUbicacion.getText()) + "'," + actualizar + ");");
            } catch (SQLException ex) {

            }finally{
                s.close();
                con.close();
            }
        } catch (Exception e) {
            e.getMessage();
        }
        Limpiar();

        CargarTabla(null, "todo");
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void Limpiar() {
        txtDireccion.setText("");
        txtHamachi.setText("");
        txtLocacion.setText("");
        txtMac.setText("");
        txtNombre.setText("");
        txtPropietario.setText("");
        txtTipo.setText("");
        txtUbicacion.setText("");

        btnGroup.clearSelection();
    }
    
    public void CambiarColor()
    {
    this.getContentPane().setBackground(Color.WHITE);
    pnlAgregarMaquina.setBackground(Color.WHITE);
    pnlModuloEliminar.setBackground(Color.WHITE);
    pnlBotonera.setBackground(Color.WHITE);
    pnlModuloAgregar.setBackground(Color.WHITE);
    pnlInformacionPreliminar.setBackground(Color.white);
    tablaAgregar.setBackground(Color.white);
    pnlModuloEliminar.setBackground(Color.WHITE);
    pnlFiltrarPor.setBackground(Color.WHITE);

    pnlInformacionMa.setBackground(Color.WHITE);
    }

    public void ListarVideos(String mac) {
        videos.clear();
        System.out.println(mac);
        try {
            Connection con = Conexion.getConexionMySQL();
            Statement s = con.createStatement();
            try (ResultSet rs = s.executeQuery("SELECT video1, video2, video3, video4, video5, video6, video7, video8, video9, video10, video11, video12, video13, video14, video15, video16, video17, video18, video19, video20  FROM maquinas WHERE mac='" + Global.Encriptar(mac) + "'")) {
                while (rs.next()) {
                    for(int i = 1; i < 21; i++){
                        videos.add(i+" = " + Global.Desencriptar(rs.getString(i)));
                        System.out.println(i+" = " + Global.Desencriptar(rs.getString(i)));
                    }
                }
                
                Modelo m = new Modelo();
                m.setModelo(videos);
                listVideos.setModel(m);

                rs.close();
            }
            s.close();
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar los videos\n\nError: "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar los videos\n\nError: "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    public void CargarTabla(JComboBox cmb, String tipo) {
        ArrayList<String> fila = new ArrayList<>();
        if (cmb != null) {
            if (cmb.getSelectedItem().toString().contains("--")) {
                return;
            }
        }
        if (tipo.equals("todo")) {
            tablaAgregar.setModel(new DefaultTableModel());
        }
        tablaMostrarEliminar.setModel(new DefaultTableModel());
        try {
            String[] nombre = {"Mac", "Nombre", "Hamachi_ip", "Tipo", "Propietario", "Direccion", "Locacion", "Ubicacion", "Actualizable"};
            model = new DefaultTableModel(null, nombre);
            Connection con = Conexion.getConexionMySQL();
            Statement s = con.createStatement();
            ResultSet rs = null;
            if (tipo.equals("todo")) {
                rs = s.executeQuery("SELECT * FROM maquinas");
            } else {
                rs = s.executeQuery("SELECT * FROM maquinas WHERE " + tipo + "='" + Global.Encriptar(cmb.getSelectedItem().toString()) + "'");
            }

            while (rs.next()) {
                fila.clear();
                fila.add(Global.Desencriptar(rs.getString("mac")));
                fila.add(Global.Desencriptar(rs.getString("nombre")));
                fila.add(Global.Desencriptar(rs.getString("hamachi_ip")));
                fila.add(Global.Desencriptar(rs.getString("tipo")));
                fila.add(Global.Desencriptar(rs.getString("propietario")));
                fila.add(Global.Desencriptar(rs.getString("direccion")));
                fila.add(Global.Desencriptar(rs.getString("locacion")));
                fila.add(Global.Desencriptar(rs.getString("ubicacion")));
                if (rs.getBoolean("actualizar")) {
                    fila.add("Actualizando");
                } else {
                    fila.add("No Actualizando");
                }
                    
                
                model.addRow(fila.toArray());

            }

            tablaMostrarEliminar.setModel(model);
            if (tipo.equals("todo")) {
                tablaAgregar.setModel(model);
            }
            rs.close();
            s.close();
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar las mac: \n\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar las mac: \n\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            System.out.println("10% 2");

        }
    }

    private class Cargar extends SwingWorker<Void, Void> {

        JComboBox cmb;
        String tipo;
        ArrayList<String> lista;

        public Cargar(JComboBox cmb, String tipo, ArrayList<String> lista) {
            this.cmb = cmb;
            this.tipo = tipo;
            this.lista = lista;
        }

        @Override
        public Void doInBackground() {
            lista.clear();
            try {
                Connection con = Conexion.getConexionMySQL();
                Statement s = con.createStatement();
                try (ResultSet rs = s.executeQuery("select " + tipo + " from maquinas")) {
                    lista.add("--Seleccione--");
                    while (rs.next()) {
                        lista.add(Global.Desencriptar(rs.getString(1)));
                    }
                    Modelo m = new Modelo();
                    m.setModelo(lista);
                    if (m.getSize() > 0) {
                        m.setSelectedItem(m.getElementAt(0));
                    }
                    cmb.setModel(m);
                    rs.close();
                    s.close();
                    con.close();
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No se pudo cargar las mac, por favor refrsque el programa", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No se pudo cargar las mac, por favor refrsque el programa", "Error", JOptionPane.ERROR_MESSAGE);
            }
            return null;
        }

    }
    
    public void Cerrar(){
        this.dispose();
    }

    private class Start extends SwingWorker<Void, Void> {

        @Override
        public Void doInBackground() {
            Carga c = new Carga();
            c.setVisible(true);
            Cerrar();
            Principal p = new Principal();
            while (c.pbCarga.getValue() < 100) {
                c.pbCarga.setValue(Math.round(Global.carga));
                c.pbCarga.setString(Math.round(Global.carga) + "%");
            }
            p.setVisible(true);
            c.dispose();
            return null;
        }
    }

    private void txtMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMacActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAgregarMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMaquinaActionPerformed
        // TODO add your handling code here:
        pnlModuloAgregar.setVisible(true);
        pnlModuloEliminar.setVisible(false);
    }//GEN-LAST:event_btnAgregarMaquinaActionPerformed

    private void BtnEliminarMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarMaquinaActionPerformed
        // TODO add your handling code here:
        pnlModuloAgregar.setVisible(false);
        pnlModuloEliminar.setVisible(true);
    }//GEN-LAST:event_BtnEliminarMaquinaActionPerformed

    private void cmbMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMacActionPerformed
        // TODO add your handling code here:
        CargarTabla(cmbMac, "mac");
        ListarVideos(cmbMac.getSelectedItem().toString());
    }//GEN-LAST:event_cmbMacActionPerformed

    private void cmbDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDuenoActionPerformed
        // TODO add your handling code here:
        CargarTabla(cmbDueno, "propietario");
    }//GEN-LAST:event_cmbDuenoActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
        CargarTabla(cmbTipo, "tipo");
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = Conexion.getConexionMySQL();
            Statement s = con.createStatement();
            s.executeUpdate("DELETE FROM `maquinas` WHERE mac='" + Global.Encriptar(tablaMostrarEliminar.getValueAt(tablaMostrarEliminar.getSelectedRow(), 0).toString()) + "'");
            s.close();
        } catch (Exception e) {
            Global.MostrarMensaje("Error al eliminar la máquina.", "Error");
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Start().execute();
          
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CargarTabla(null, "todo");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablaMostrarEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMostrarEliminarMouseClicked
        ListarVideos(tablaMostrarEliminar.getModel().getValueAt(tablaMostrarEliminar.getSelectedRow(),0).toString());
    }//GEN-LAST:event_tablaMostrarEliminarMouseClicked

    private void txtHamachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHamachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHamachiActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
     System.exit(0);
      
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maquinas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminarMaquina;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarMaquina;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbDueno;
    private javax.swing.JComboBox<String> cmbMac;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listVideos;
    private javax.swing.JPanel pnlAgregarMaquina;
    private javax.swing.JPanel pnlBarra;
    private javax.swing.JPanel pnlBotonera;
    private javax.swing.JPanel pnlFiltrarPor;
    private javax.swing.JPanel pnlInformacionMa;
    private javax.swing.JPanel pnlInformacionPreliminar;
    private javax.swing.JPanel pnlModuloAgregar;
    private javax.swing.JPanel pnlModuloEliminar;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbSi;
    private javax.swing.JTable tablaAgregar;
    private javax.swing.JTable tablaMostrarEliminar;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtHamachi;
    private javax.swing.JTextField txtLocacion;
    private javax.swing.JTextField txtMac;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}